
services:
  mysql:
    image: mysql:8.4
    container_name: mysql8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: jeogieottae
      TZ: Asia/Seoul
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --local-infile=1
      --innodb_redo_log_capacity=4G
    ports:
      - "3307:3306"
    volumes:
      - ./csv:/var/lib/mysql-files
      - ./mysql-init:/docker-entrypoint-initdb.d
volumes:
    mysql-data:
