spring:
  application:
    name: jeogieottae
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATA_SOURCE_URL}
    username: ${DATA_SOURCE_USERNAME}
    password: ${DATA_SOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: optional:file:.env[.properties]

jwt:
  secret:
    key: ${JWT_SECRET_KEY}