name: CI/CD Jeogieottae

on:
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Give execute permission to gradlew
        run: chmod +x gradlew

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Build Docker Image with Gradle cache
        run: |
          docker buildx build \
            --build-arg GRADLE_USER_HOME=/home/gradle/.gradle \
            --cache-to=type=local,dest=/tmp/.gradle-cache,mode=max \
            --cache-from=type=local,src=/tmp/.gradle-cache \
            --no-cache \
            -t ${{ secrets.DOCKER_USERNAME }}/jeogieottaeserver:latest \
            --load .

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/jeogieottaeserver:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pull latest Docker image"
            docker pull ${{ secrets.DOCKER_USERNAME }}/jeogieottaeserver:latest
            
            echo "Stop containers using port 8080"
            docker ps -q --filter "publish=8080" | xargs -r docker stop
            docker ps -aq --filter "publish=8080" | xargs -r docker rm
            
            echo "Remove old containers named jeogieottae (if any)"
            docker rm -f jeogieottae || true
            
            echo "Clean unused images"
            docker image prune -f
            
            echo "Run new container"
            docker run -d --name jeogieottae -p 8080:8080 \
            -e "SPRING_DATASOURCE_URL=jdbc:mysql://database-1.c0pu8i0ekw5y.us-east-1.rds.amazonaws.com:3306/jeogieottae?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul" \
            -e "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" \
            -e "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" \
            -e "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" \
            -e "SPRING_DATA_REDIS_HOST=${{secrets.SPRING_DATA_REDIS_HOST}}" \
            -e "SERVER_NAME=${{secrets.SERVER_NAME}}" \
            dperado/jeogieottaeserver:latest
